name: Build and Push Java Service to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev-studytrack
	
	services:
	      postgres:
	        image: postgres:15
	        env:
	          POSTGRES_DB: studytrack
	          POSTGRES_USER: postgres
	          POSTGRES_PASSWORD: postgres
	        ports:
	          - 5432:5432
	        options: >-
	          --health-cmd pg_isready
	          --health-interval 10s
	          --health-timeout 5s
	          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-java-service:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-java-service:latest
